version: "3.8"

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynet
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]

  web:
    image: dipesh230904/devops-web:latest
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
    ports:
      - "8000:8000"
    networks:
      - mynet
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 10s

networks:
  mynet:
    driver: overlay

volumes:
  pgdata:
